import {
  Employee,
  AttendanceRecord,
  LeaveRequest,
  Shift,
  DashboardStats,
  ActivityItem,
} from '@/types';

export const initialStats: DashboardStats = {
  totalEmployees: 142,
  presentToday: 118,
  lateToday: 12,
  absentToday: 4,
  onLeaveToday: 8,
};

export const initialEmployees: Employee[] = [
  {
    id: 'EMP-001',
    name: 'Admin User',
    email: 'admin@company.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    position: 'VP of People & Culture',
    role: 'ADMIN',
    status: 'Active',
    joinDate: '2021-03-15',
    phone: '+1 (555) 234-5678',
    address: '742 Evergreen Terrace, Seattle, WA',
    attendanceSummary: {
      presentRate: 98.2,
      presentDays: 165,
      lateDays: 2,
      absentDays: 1,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 5,
      sickUsed: 2,
      remaining: 11,
    },
  },
  {
    id: 'EMP-002',
    name: 'Alex Rivera',
    email: 'alex.rivera@company.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    position: 'Staff Software Architect',
    role: 'EMPLOYEE',
    status: 'Active',
    joinDate: '2022-01-10',
    phone: '+1 (555) 345-6789',
    address: '1204 Pine Street, San Francisco, CA',
    attendanceSummary: {
      presentRate: 95.8,
      presentDays: 161,
      lateDays: 5,
      absentDays: 2,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 8,
      sickUsed: 1,
      remaining: 9,
    },
  },
  {
    id: 'EMP-003',
    name: 'Emily Zhao',
    email: 'emily.zhao@company.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    position: 'Lead Product Designer',
    role: 'HR',
    status: 'Active',
    joinDate: '2022-06-01',
    phone: '+1 (555) 456-7890',
    address: '58 Maple Avenue, Austin, TX',
    attendanceSummary: {
      presentRate: 99.4,
      presentDays: 167,
      lateDays: 1,
      absentDays: 0,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 6,
      sickUsed: 0,
      remaining: 12,
    },
  },
  {
    id: 'EMP-004',
    name: 'David Kim',
    email: 'david.kim@company.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    position: 'Senior Backend Developer',
    role: 'EMPLOYEE',
    status: 'On Leave',
    joinDate: '2023-02-20',
    phone: '+1 (555) 567-8901',
    address: '890 Broadway Blvd, New York, NY',
    attendanceSummary: {
      presentRate: 92.3,
      presentDays: 155,
      lateDays: 8,
      absentDays: 5,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 15,
      annualUsed: 10,
      sickUsed: 3,
      remaining: 2,
    },
  },
  {
    id: 'EMP-005',
    name: 'Marcus Vance',
    email: 'marcus.vance@company.com',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Finance & Operations',
    position: 'Senior Financial Analyst',
    role: 'EMPLOYEE',
    status: 'Active',
    joinDate: '2021-11-05',
    phone: '+1 (555) 678-9012',
    address: '320 Lakeview Drive, Chicago, IL',
    attendanceSummary: {
      presentRate: 97.6,
      presentDays: 164,
      lateDays: 3,
      absentDays: 1,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 7,
      sickUsed: 1,
      remaining: 10,
    },
  },
  {
    id: 'EMP-006',
    name: 'Elena Rostova',
    email: 'elena.rostova@company.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    position: 'Growth Marketing Manager',
    role: 'EMPLOYEE',
    status: 'Active',
    joinDate: '2023-05-15',
    phone: '+1 (555) 789-0123',
    address: '412 Ocean Parkway, Miami, FL',
    attendanceSummary: {
      presentRate: 96.4,
      presentDays: 162,
      lateDays: 4,
      absentDays: 2,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 15,
      annualUsed: 4,
      sickUsed: 0,
      remaining: 11,
    },
  },
  {
    id: 'EMP-007',
    name: 'Tariq Mansoor',
    email: 'tariq.mansoor@company.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    position: 'DevOps & Cloud Engineer',
    role: 'EMPLOYEE',
    status: 'Active',
    joinDate: '2022-09-01',
    phone: '+1 (555) 890-1234',
    address: '67 Silicon Valley Way, San Jose, CA',
    attendanceSummary: {
      presentRate: 98.8,
      presentDays: 166,
      lateDays: 2,
      absentDays: 0,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 3,
      sickUsed: 1,
      remaining: 14,
    },
  },
  {
    id: 'EMP-008',
    name: 'Chloe Bennett',
    email: 'chloe.bennett@company.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    position: 'HR Talent Acquisition Specialist',
    role: 'HR',
    status: 'Active',
    joinDate: '2023-08-10',
    phone: '+1 (555) 901-2345',
    address: '150 Sunset Boulevard, Los Angeles, CA',
    attendanceSummary: {
      presentRate: 95.2,
      presentDays: 160,
      lateDays: 6,
      absentDays: 2,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 15,
      annualUsed: 5,
      sickUsed: 2,
      remaining: 8,
    },
  },
  {
    id: 'EMP-009',
    name: 'Lucas Dupont',
    email: 'lucas.dupont@company.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    position: 'Senior UX Researcher',
    role: 'EMPLOYEE',
    status: 'Inactive',
    joinDate: '2020-04-12',
    phone: '+1 (555) 012-3456',
    address: '22 Beacon Street, Boston, MA',
    attendanceSummary: {
      presentRate: 91.0,
      presentDays: 153,
      lateDays: 10,
      absentDays: 5,
      totalDays: 168,
    },
    leaveSummary: {
      annualTotal: 18,
      annualUsed: 18,
      sickUsed: 4,
      remaining: 0,
    },
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'ATT-001',
    employeeId: 'EMP-001',
    employeeName: 'Admin User',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2026-09-17',
    checkIn: '08:45 AM',
    checkOut: '05:30 PM',
    status: 'Present',
    workingHours: '8h 45m',
    shift: 'General Office Shift',
  },
  {
    id: 'ATT-002',
    employeeId: 'EMP-002',
    employeeName: 'Alex Rivera',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-09-17',
    checkIn: '09:22 AM',
    checkOut: '06:15 PM',
    status: 'Late',
    workingHours: '8h 53m',
    shift: 'General Office Shift',
    notes: 'Traffic delay on Highway 101',
  },
  {
    id: 'ATT-003',
    employeeId: 'EMP-003',
    employeeName: 'Emily Zhao',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Product & Design',
    date: '2026-09-17',
    checkIn: '08:55 AM',
    checkOut: '05:40 PM',
    status: 'Present',
    workingHours: '8h 45m',
    shift: 'General Office Shift',
  },
  {
    id: 'ATT-004',
    employeeId: 'EMP-004',
    employeeName: 'David Kim',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-09-17',
    checkIn: null,
    checkOut: null,
    status: 'Leave',
    workingHours: null,
    notes: 'Approved Annual Leave',
  },
  {
    id: 'ATT-005',
    employeeId: 'EMP-005',
    employeeName: 'Marcus Vance',
    employeeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Finance & Operations',
    date: '2026-09-17',
    checkIn: '08:50 AM',
    checkOut: '05:35 PM',
    status: 'Present',
    workingHours: '8h 45m',
    shift: 'General Office Shift',
  },
  {
    id: 'ATT-006',
    employeeId: 'EMP-006',
    employeeName: 'Elena Rostova',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    date: '2026-09-17',
    checkIn: '09:14 AM',
    checkOut: '06:05 PM',
    status: 'Late',
    workingHours: '8h 51m',
    shift: 'General Office Shift',
  },
  {
    id: 'ATT-007',
    employeeId: 'EMP-007',
    employeeName: 'Tariq Mansoor',
    employeeAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    date: '2026-09-17',
    checkIn: '07:05 AM',
    checkOut: '03:45 PM',
    status: 'Present',
    workingHours: '8h 40m',
    shift: 'Morning Shift',
  },
  {
    id: 'ATT-008',
    employeeId: 'EMP-008',
    employeeName: 'Chloe Bennett',
    employeeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    date: '2026-09-17',
    checkIn: null,
    checkOut: null,
    status: 'Absent',
    workingHours: null,
    notes: 'Unnotified absence - Follow up initiated',
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'LR-101',
    employeeId: 'EMP-004',
    employeeName: 'David Kim',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'Annual Leave',
    startDate: '2026-09-16',
    endDate: '2026-09-18',
    duration: 3,
    reason: 'Family vacation and personal recharge',
    status: 'Approved',
    appliedAt: '2026-09-10',
  },
  {
    id: 'LR-102',
    employeeId: 'EMP-002',
    employeeName: 'Alex Rivera',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'Sick Leave',
    startDate: '2026-09-22',
    endDate: '2026-09-23',
    duration: 2,
    reason: 'Scheduled minor dental surgery and recovery',
    status: 'Pending',
    appliedAt: '2026-09-15',
  },
  {
    id: 'LR-103',
    employeeId: 'EMP-006',
    employeeName: 'Elena Rostova',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Marketing',
    leaveType: 'Casual Leave',
    startDate: '2026-09-25',
    endDate: '2026-09-25',
    duration: 1,
    reason: 'Attending sibling graduation ceremony',
    status: 'Pending',
    appliedAt: '2026-09-16',
  },
  {
    id: 'LR-104',
    employeeId: 'EMP-007',
    employeeName: 'Tariq Mansoor',
    employeeAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Engineering',
    leaveType: 'Annual Leave',
    startDate: '2026-10-01',
    endDate: '2026-10-08',
    duration: 6,
    reason: 'Overseas travel with spouse',
    status: 'Pending',
    appliedAt: '2026-09-14',
  },
  {
    id: 'LR-105',
    employeeId: 'EMP-005',
    employeeName: 'Marcus Vance',
    employeeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    department: 'Finance & Operations',
    leaveType: 'Casual Leave',
    startDate: '2026-09-08',
    endDate: '2026-09-08',
    duration: 1,
    reason: 'Vehicle inspection and registration appointment',
    status: 'Approved',
    appliedAt: '2026-09-02',
  },
  {
    id: 'LR-106',
    employeeId: 'EMP-008',
    employeeName: 'Chloe Bennett',
    employeeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Human Resources',
    leaveType: 'Unpaid Leave',
    startDate: '2026-09-05',
    endDate: '2026-09-07',
    duration: 3,
    reason: 'Extended personal leave during project milestone',
    status: 'Rejected',
    appliedAt: '2026-08-28',
  },
];

export const initialShifts: Shift[] = [
  {
    id: 'SH-01',
    name: 'General Office Shift',
    startTime: '09:00 AM',
    endTime: '06:00 PM',
    breakDuration: '60 mins',
    employeeCount: 94,
    status: 'Active',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
  {
    id: 'SH-02',
    name: 'Morning Shift',
    startTime: '07:00 AM',
    endTime: '03:30 PM',
    breakDuration: '45 mins',
    employeeCount: 26,
    status: 'Active',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 'SH-03',
    name: 'Evening Shift',
    startTime: '03:00 PM',
    endTime: '11:30 PM',
    breakDuration: '45 mins',
    employeeCount: 14,
    status: 'Active',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
  {
    id: 'SH-04',
    name: 'Night Operations Shift',
    startTime: '11:00 PM',
    endTime: '07:30 AM',
    breakDuration: '60 mins',
    employeeCount: 8,
    status: 'Active',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },
];

export const initialActivities: ActivityItem[] = [
  {
    id: 'ACT-01',
    title: 'New leave application submitted',
    description: 'Elena Rostova applied for 1 day Casual Leave (Sep 25).',
    timestamp: '15 mins ago',
    type: 'leave',
    badgeColor: 'blue',
  },
  {
    id: 'ACT-02',
    title: 'Late check-in recorded',
    description: 'Alex Rivera clocked in at 09:22 AM (+22 min delay).',
    timestamp: '42 mins ago',
    type: 'attendance',
    badgeColor: 'amber',
  },
  {
    id: 'ACT-03',
    title: 'Shift roster updated',
    description: 'Tariq Mansoor reassigned to Morning Shift by Administrator.',
    timestamp: '2 hours ago',
    type: 'shift',
    badgeColor: 'purple',
  },
  {
    id: 'ACT-04',
    title: 'Annual leave approved',
    description: 'David Kim leave request for 3 days was approved.',
    timestamp: 'Yesterday at 4:30 PM',
    type: 'leave',
    badgeColor: 'emerald',
  },
  {
    id: 'ACT-05',
    title: 'Employee profile updated',
    description: 'Chloe Bennett changed contact telephone number.',
    timestamp: 'Yesterday at 2:15 PM',
    type: 'employee',
    badgeColor: 'slate',
  },
];

export const weeklyAttendanceTrend = [
  { day: 'Mon', present: 122, late: 8, absent: 4, rate: '91%' },
  { day: 'Tue', present: 126, late: 6, absent: 2, rate: '94%' },
  { day: 'Wed', present: 124, late: 9, absent: 3, rate: '92%' },
  { day: 'Thu', present: 118, late: 12, absent: 4, rate: '88%' },
  { day: 'Fri', present: 115, late: 15, absent: 6, rate: '86%' },
];

export const departmentStats = [
  { department: 'Engineering', total: 48, present: 43, rate: 89.6 },
  { department: 'Human Resources', total: 12, present: 11, rate: 91.7 },
  { department: 'Product & Design', total: 24, present: 23, rate: 95.8 },
  { department: 'Finance & Operations', total: 28, present: 27, rate: 96.4 },
  { department: 'Marketing', total: 30, present: 27, rate: 90.0 },
];
